apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repositories.yaml
  - cilium.yaml
  - cert-manager.yaml
  - openebs.yaml
  - istio.yaml
  - envoy-ingress.yaml
  - tetragon.yaml
  - kyverno.yaml
  - kubescape.yaml
  - falco.yaml
  - metrics-server.yaml
  - trivy.yaml
  - contour.yaml
